{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openwearables.health",
    "module": "sdk",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.11.1.aar",
          "url": "sdk-0.11.1.aar",
          "size": 266213,
          "sha512": "ac41dbaf4a947dd3b0752aae62af0130dd8dac6122a16c82db5b3b396f63d62ad683ee0bd8e56f4dd63af7a7bfc1887f7d45c86d45ea426c712a30d844f3bae0",
          "sha256": "290cb165e47c62cc583109f5844e7a239f582fe1c614fb27e9694361ce1fdf67",
          "sha1": "76556e211d8c53175d77450ae57c909870685e4e",
          "md5": "484ba77d05c533a1aec5361fd0f0a1a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.samsung.android.health",
          "module": "data",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.11.1.aar",
          "url": "sdk-0.11.1.aar",
          "size": 266213,
          "sha512": "ac41dbaf4a947dd3b0752aae62af0130dd8dac6122a16c82db5b3b396f63d62ad683ee0bd8e56f4dd63af7a7bfc1887f7d45c86d45ea426c712a30d844f3bae0",
          "sha256": "290cb165e47c62cc583109f5844e7a239f582fe1c614fb27e9694361ce1fdf67",
          "sha1": "76556e211d8c53175d77450ae57c909870685e4e",
          "md5": "484ba77d05c533a1aec5361fd0f0a1a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-0.11.1-sources.jar",
          "url": "sdk-0.11.1-sources.jar",
          "size": 42775,
          "sha512": "1cd6e5df781f91452d04b27c8a60b5e8705ba8969c618f9c29deb7813826a9ead8b51926f17b928fa0d68611838c035bbf06ff9c7287bafec52f27b112708e5d",
          "sha256": "0d002f2bf41e3d0182f9c23a7ec8818706e3714f09b3fa5bd62ed461ab50290a",
          "sha1": "99d7318dd1aed2da15244e1fb669f92b645b2596",
          "md5": "89cee6f11a8220cb28389950b48cb40c"
        }
      ]
    }
  ]
}
